import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { AddressForm } from '../components/AddressForm'
import { Button } from '../components/ui/Button'
import { EmptyState } from '../components/ui/EmptyState'
import { ErrorState } from '../components/ui/ErrorState'
import { Skeleton } from '../components/ui/Skeleton'
import { addressSchema, governorateKeys, type AddressInput } from '../domain/schemas'
import { formatMoney } from '../domain/money'
import { useCart } from '../hooks/useCart'
import { useAuthState } from '../hooks/useAuthState'
import { supabase } from '../lib/supabaseClient'
import { IdempotencyKeyLifecycle, mapCheckoutError, orderTotalPreview } from '../features/orders/orderLogic'
import type { Address } from '../domain/types'

let checkoutDraft: AddressInput | undefined
const lifecycle = new IdempotencyKeyLifecycle()
function addrInput(address: Address): AddressInput { return { fullName: address.fullName, phone: address.phone, governorate: address.governorate as typeof governorateKeys[number], city: address.city, street: address.street, building: address.building, notes: address.notes } }

function Summary({ cart, shippingFee }: { cart: ReturnType<typeof useCart>; shippingFee: number }) { const { t, i18n } = useTranslation(); const preview = orderTotalPreview(cart.items.map((item) => ({ unitPriceSnapshot: item.product.price, quantity: item.quantity })), shippingFee); return <aside className="checkout-summary"><h2>{t('checkout.summary')}</h2>{cart.items.map((item) => <div className="summary-line" key={item.product.id}><span>{i18n.language === 'ar' ? item.product.nameAr : item.product.nameEn} × {item.quantity}</span><strong>{formatMoney(item.product.price * item.quantity, i18n.language as 'ar' | 'en')}</strong></div>)}<dl className="totals"><div><dt>{t('cart.subtotal')}</dt><dd>{formatMoney(preview.subtotal, i18n.language as 'ar' | 'en')}</dd></div><div><dt>{t('orders.shippingFee')}</dt><dd>{formatMoney(preview.shippingFee, i18n.language as 'ar' | 'en')}</dd></div><div><dt>{t('orders.total')}</dt><dd>{formatMoney(preview.total, i18n.language as 'ar' | 'en')}</dd></div></dl></aside> }

export function CheckoutPage() {
  const { t, i18n } = useTranslation(); const navigate = useNavigate(); const cart = useCart(); const auth = useAuthState(); const [addresses, setAddresses] = useState<Address[]>([]); const [selected, setSelected] = useState<string | null>(null); const [step, setStep] = useState<1 | 2>(1); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [adding, setAdding] = useState(false); const [submitting, setSubmitting] = useState(false); const [changes, setChanges] = useState(cart.changes); const [message, setMessage] = useState<string | null>(null); const [shippingFee, setShippingFee] = useState(0)
  const load = () => { setLoading(true); void Promise.all([supabase.from('addresses').select('*').order('is_default', { ascending: false }).order('created_at', { ascending: true }), supabase.from('app_settings').select('shipping_flat_fee').eq('id', 1).single()]).then(([addressResult, settingsResult]) => { if (addressResult.error || settingsResult.error) setFailed(true); else { const rows = (addressResult.data ?? []) as Address[]; setAddresses(rows); setSelected(rows.find((address) => (address as Address & { is_default?: boolean }).is_default)?.id ?? rows[0]?.id ?? null); setShippingFee((settingsResult.data as { shipping_flat_fee: number }).shipping_flat_fee) } }).finally(() => setLoading(false)) }
  useEffect(() => { void cart.revalidate().then(setChanges).catch(() => setMessage('CHECKOUT_ERROR')); load() }, [])
  const selectedAddress = addresses.find((address) => address.id === selected)
  const addAddress = async (value: AddressInput) => { setAdding(true); const result = await supabase.from('addresses').insert({ ...value, notes: value.notes }).select().single(); if (result.error) setMessage(result.error.message); else { const address = result.data as Address; if (!addresses.length) await supabase.rpc('set_default_address', { p_address_id: address.id }); setAddresses((current) => [...current, address]); setSelected(address.id); setStep(2) } setAdding(false) }
  const goReview = async () => { if (!selected) return; const result = await cart.revalidate().catch(() => null); if (result === null) { setMessage('CHECKOUT_ERROR'); return } setChanges(result); lifecycle.enterReview(); setStep(2) }
  const place = async () => { if (!selected || submitting) return; setSubmitting(true); setMessage(null); const result = await supabase.rpc('place_order', { p_idempotency_key: lifecycle.current(), p_address_id: selected, p_payment_method: 'COD' }); if (result.error) { const action = mapCheckoutError(result.error); if (action.kind === 'stockConflict') { navigate(`/${i18n.language}/cart`, { state: { highlightProductIds: action.productIds } }); setSubmitting(false); return } if (action.kind === 'priceChanged') { const next = await cart.revalidate(); setChanges(next); setSubmitting(false); return } if (action.kind === 'emptyCart') { setMessage('CART_EMPTY'); setSubmitting(false); return } if (action.kind === 'sessionExpired') { checkoutDraft = selectedAddress ? addrInput(selectedAddress) : checkoutDraft; navigate(`/${i18n.language}/login?returnTo=${encodeURIComponent(`/${i18n.language}/checkout`)}`); setSubmitting(false); return } setMessage(action.kind === 'verifyRequired' ? 'AUTH_VERIFY_REQUIRED' : 'CHECKOUT_ERROR'); setSubmitting(false); return }; lifecycle.discardAfterSuccess(); await cart.revalidate(); const data = result.data as { order_id: string }; navigate(`/${i18n.language}/checkout/confirmation/${data.order_id}`, { replace: true }) }
  if (loading) return <section className="container checkout-page"><Skeleton className="listing-skeleton" /></section>
  if (failed) return <ErrorState message={t('messages.CHECKOUT_ERROR')} action={t('actions.tryAgain')} onAction={load} />
  if (!cart.items.length) return <EmptyState message={t('messages.CART_EMPTY')} action={t('actions.continueShopping')} onAction={() => navigate(`/${i18n.language}/shop`)} />
  return <section className="container checkout-page"><h1 className="page-heading">{t('pages.checkout')}</h1><ol className="checkout-steps"><li className={step === 1 ? 'active' : ''}>{t('checkout.addressStep')}</li><li className={step === 2 ? 'active' : ''}>{t('checkout.reviewStep')}</li><li>{t('checkout.doneStep')}</li></ol><div className="checkout-grid"><div>{message && <div className="form-alert" role="alert">{t(`messages.${message}`, { defaultValue: t('messages.CHECKOUT_ERROR') })}{message === 'AUTH_VERIFY_REQUIRED' && <p><Link to={`/${i18n.language}/verify-email`}>{t('actions.resendLink')}</Link></p>}</div>}{step === 1 ? <><h2>{t('checkout.chooseAddress')}</h2>{addresses.map((address) => <label className="address-option" key={address.id}><input type="radio" checked={selected === address.id} onChange={() => { setSelected(address.id); void supabase.rpc('set_default_address', { p_address_id: address.id }) }} />{address.fullName} — {t(`governorates.${address.governorate}`)}, {address.city}</label>)}{addresses.length > 0 && <Button disabled={!selected} onClick={() => void goReview()}>{t('checkout.reviewOrder')}</Button>}<h2>{addresses.length ? t('checkout.addAddress') : t('checkout.enterAddress')}</h2><AddressForm initial={checkoutDraft} onSubmit={(value) => void addAddress(value)} submitting={adding} /></> : <><h2>{t('checkout.reviewOrder')}</h2>{changes.length > 0 && <div className="form-alert" role="alert">{changes.map((change) => <p key={`${change.code}-${change.productId}`}>{t(`messages.${change.code}`, { name: i18n.language === 'ar' ? change.nameAr : change.nameEn, n: change.n })}</p>)}</div>}<p>{t('checkout.payment')}: <strong>{t('orders.cashOnDelivery')}</strong></p><p>{selectedAddress?.fullName}, {selectedAddress?.city}</p><Button onClick={() => void place()} loading={submitting}>{t('checkout.placeOrder')}</Button></>}</div><Summary cart={cart} shippingFee={shippingFee} /></div></section>
}

export function ConfirmationPage() {
  const { t, i18n } = useTranslation(); const navigate = useNavigate(); const { orderId } = useParams(); const [order, setOrder] = useState<{ order_number: string; status: string; total: number; subtotal: number; shipping_fee: number } | null>(null); const [failed, setFailed] = useState(false)
  useEffect(() => { if (!orderId) return; void supabase.from('orders').select('order_number,status,total,subtotal,shipping_fee').eq('id', orderId).maybeSingle().then(({ data, error }) => { if (error || !data) setFailed(true); else setOrder(data) }) }, [orderId])
  if (!order && !failed) return <section className="container"><Skeleton className="listing-skeleton" /></section>
  if (failed || !order) return <ErrorState message={t('messages.PAGE_404')} action={t('actions.goHome')} onAction={() => navigate(`/${i18n.language}`)} />
  return <section className="container confirmation-page"><h1 className="page-heading">{t('pages.confirmation')}</h1><p className="form-success">{t('checkout.orderPlaced')}</p><h2>{order.order_number}</h2><p className="status-badge">{t(`orderStatus.${order.status}`)}</p><p>{t('orders.total')}: {formatMoney(order.total, i18n.language as 'ar' | 'en')}</p><Link to={`/${i18n.language}/account/orders/${orderId}`}>{t('checkout.viewOrder')}</Link></section>
}
