import { useEffect, useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { supabase } from '../lib/supabaseClient'
import { getAvailability } from '../domain/inventory'
import { allowedProductActions, buildProductUpdatePayload, parsePriceToPiasters, reorderProductImages, setPrimaryProductImage, type EditableProductImage, type ProductAction } from '../domain/productAdmin'
import { productSchema } from '../domain/schemas'
import { MAX_IMAGES_PER_PRODUCT, MAX_IMAGE_MB } from '../config/businessConfig'
import type { ProductStatus } from '../domain/types'

type ProductRow = {
  id: string; sku: string; name_ar: string; name_en: string; brand: string; description_ar: string; description_en: string
  price: number; stock: number; low_stock_override: number | null; status: ProductStatus; featured: boolean
  specs: Record<string, string | number>; updated_at: string; product_images: EditableProductImage[]
}
type FormState = { sku: string; nameAr: string; nameEn: string; brand: string; descriptionAr: string; descriptionEn: string; price: string; stock: string; low: string; caseSize: string; waterResistance: string; movement: string; material: string; strap: string; gender: string }
const blank: FormState = { sku: '', nameAr: '', nameEn: '', brand: '', descriptionAr: '', descriptionEn: '', price: '', stock: '0', low: '', caseSize: '40', waterResistance: '30', movement: 'automatic', material: 'stainless_steel', strap: 'steel', gender: 'unisex' }
const fileTypes = ['image/jpeg', 'image/png', 'image/webp']
function errorCode(error: { message?: string } | null): string { return error?.message === '23505' ? 'PRODUCT_SKU_TAKEN' : error?.message ?? 'PAGE_500' }
function Badge({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`admin-badge ${tone}`}>{children}</span> }
function formatForm(product: ProductRow): FormState { return { sku: product.sku, nameAr: product.name_ar, nameEn: product.name_en, brand: product.brand, descriptionAr: product.description_ar, descriptionEn: product.description_en, price: (product.price / 100).toFixed(2), stock: String(product.stock), low: product.low_stock_override === null ? '' : String(product.low_stock_override), caseSize: String(product.specs.caseSize ?? 40), waterResistance: String(product.specs.waterResistance ?? 30), movement: String(product.specs.movement ?? 'automatic'), material: String(product.specs.material ?? 'stainless_steel'), strap: String(product.specs.strap ?? 'steel'), gender: String(product.specs.gender ?? 'unisex') } }

export function ProductEditPage({ id }: { id: string }) {
  const { t, i18n } = useTranslation(); const navigate = useNavigate()
  const [product, setProduct] = useState<ProductRow | null>(null); const [form, setForm] = useState(blank); const [initial, setInitial] = useState(blank); const [loadedAt, setLoadedAt] = useState<string | null>(null)
  const [images, setImages] = useState<EditableProductImage[]>([]); const [error, setError] = useState<string | null>(null); const [imageError, setImageError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [imageBusy, setImageBusy] = useState(false); const [progress, setProgress] = useState<Record<string, number>>({})
  const dirty = JSON.stringify(form) !== JSON.stringify(initial)
  useEffect(() => { void load() }, [id])
  useEffect(() => { const guard = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = '' } }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard) }, [dirty])
  async function load() { const result = await supabase.from('products').select('*, product_images(*)').eq('id', id).single(); if (result.error) { setError(errorCode(result.error)); return }; const next = result.data as ProductRow; setProduct(next); setLoadedAt(next.updated_at); setForm(formatForm(next)); setInitial(formatForm(next)); setImages([...next.product_images].sort((a, b) => a.position - b.position)); setError(null) }
  const set = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const cancel = () => { if (!dirty || window.confirm(  t('account.unsavedConfirm'))) navigate('/admin/products') }
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); const price = parsePriceToPiasters(form.price); const parsed = productSchema.safeParse({ sku: form.sku, nameAr: form.nameAr, nameEn: form.nameEn, brand: form.brand, descriptionAr: form.descriptionAr, descriptionEn: form.descriptionEn, price: price ?? 0, stock: Number(form.stock), lowStockThresholdOverride: form.low === '' ? null : Number(form.low), specs: { caseSize: Number(form.caseSize), waterResistance: Number(form.waterResistance), movement: form.movement, material: form.material, strap: form.strap, gender: form.gender } }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? 'INVALID_INPUT'); return }; setSaving(true); const result = await supabase.from('products').update(buildProductUpdatePayload(parsed.data)).eq('id', id).eq('updated_at', loadedAt).select().maybeSingle(); if (result.error) setError(errorCode(result.error)); else if (!result.data) setError('ADMIN_EDIT_CONFLICT'); else { setInitial(form); await load(); setError(null) }; setSaving(false) }
  async function uploadFiles(event: ChangeEvent<HTMLInputElement>) { const selected = Array.from(event.target.files ?? []); if (!selected.length || images.length + selected.length > MAX_IMAGES_PER_PRODUCT || selected.some((file) => !fileTypes.includes(file.type) || file.size > MAX_IMAGE_MB * 1024 * 1024)) { setImageError('IMAGE_INVALID'); return }; setImageBusy(true); setImageError(null); for (const [offset, file] of selected.entries()) { const ext = file.name.split('.').pop()?.toLowerCase() ?? 'jpg'; const path = `products/${id}/${crypto.randomUUID()}.${ext}`; setProgress((current) => ({ ...current, [file.name]: 0 })); const upload = await supabase.storage.from('product-images').upload(path, file); if (upload.error) { setImageError('IMAGE_INVALID'); break }; const row = await supabase.from('product_images').insert({ product_id: id, path, position: images.length + offset, is_primary: images.length === 0 && offset === 0 }).select().single(); if (row.error) { setImageError(errorCode(row.error)); break }; setImages((current) => [...current, row.data as EditableProductImage]); setProgress((current) => ({ ...current, [file.name]: 100 })) }; setImageBusy(false) }
  async function move(image: EditableProductImage, direction: 'earlier' | 'later') { const next = reorderProductImages(images, image.id, direction); if (next === images) return; setImageBusy(true); setImageError(null); const changed = next.filter((item, index) => item.position !== images[index]?.position); const result = await Promise.all(changed.map((item) => supabase.from('product_images').update({ position: item.position }).eq('id', item.id))); const failure = result.find((item) => item.error)?.error; if (failure) setImageError(errorCode(failure)); else setImages(next); setImageBusy(false) }
  async function primary(image: EditableProductImage) { setImageBusy(true); setImageError(null); const old = images.find((item) => item.is_primary); if (old && old.id !== image.id) { const first = await supabase.from('product_images').update({ is_primary: false }).eq('id', old.id); if (first.error) { setImageError(errorCode(first.error)); setImageBusy(false); return } }; const next = await supabase.from('product_images').update({ is_primary: true }).eq('id', image.id); if (next.error) setImageError(errorCode(next.error)); else setImages(setPrimaryProductImage(images, image.id)); setImageBusy(false) }
  async function remove(image: EditableProductImage) { if (!window.confirm(t('admin.removeImageConfirm'))) return; setImageBusy(true); setImageError(null); const row = await supabase.from('product_images').delete().eq('id', image.id); if (row.error) setImageError(errorCode(row.error)); else { if (!image.path.startsWith('/')) { const storage = await supabase.storage.from('product-images').remove([image.path]); if (storage.error) setImageError(errorCode(storage.error)) }; setImages((current) => current.filter((item) => item.id !== image.id).map((item, position) => ({ ...item, position }))) }; setImageBusy(false) }
  if (!product) return <section className="admin-page"><div className="admin-skeleton" aria-label={t('ui.loading')} />{error && <div role="alert">{t(`messages.${error}`, { defaultValue: t('messages.PAGE_500') })}</div>}</section>
  const availability = getAvailability({ stock: product.stock, lowStockThresholdOverride: product.low_stock_override })
  return <section className="admin-page"><div className="admin-page-title"><h1>{t('admin.editProduct')}</h1><button type="button" className="admin-link-button" onClick={cancel}>{  t('account.backToProducts')}</button></div><div className="admin-product-header"><Badge>{t(`productStatus.${product.status}`)}</Badge>{product.status === 'ACTIVE' && <Badge tone={availability.toLowerCase()}>{t(`availability.${availability}`)}</Badge>}<span>{product.sku}</span><time dateTime={product.updated_at}>{new Intl.DateTimeFormat(i18n.language, { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Cairo' }).format(new Date(product.updated_at))}</time></div>{error && <div className="admin-error" role="alert">{t(`messages.${error}`, { defaultValue: t('messages.PAGE_500') })}{error === 'ADMIN_EDIT_CONFLICT' && <button onClick={() => void load()}>{  t('actions.reload')}</button>}</div>}<form className="admin-form" onSubmit={(event) => void submit(event)}><div className="admin-form-grid">{(['sku','nameAr','nameEn','brand','price','stock','low'] as const).map((key) => <label key={key}>{t(`admin.fields.${key}`)}<input readOnly={key === 'sku'} disabled={key === 'stock'} type={['price','stock','low'].includes(key) ? 'number' : 'text'} value={form[key]} onChange={(event) => set(key, event.target.value)} /></label>)}</div><label>{t('admin.fields.descriptionAr')}<textarea value={form.descriptionAr} onChange={(event) => set('descriptionAr', event.target.value)} /></label><label>{t('admin.fields.descriptionEn')}<textarea value={form.descriptionEn} onChange={(event) => set('descriptionEn', event.target.value)} /></label><div className="admin-form-grid">{(['caseSize','waterResistance','movement','material','strap','gender'] as const).map((key) => <label key={key}>{t(`admin.fields.${key}`)}{['movement','material','strap','gender'].includes(key) ? <select value={form[key]} onChange={(event) => set(key, event.target.value)}>{(key === 'movement' ? ['automatic','manual','quartz'] : key === 'material' ? ['stainless_steel','gold','rose_gold','titanium','ceramic','other'] : key === 'strap' ? ['leather','steel','rubber','fabric','other'] : ['men','women','unisex']).map((option) => <option key={option} value={option}>{t(`specs.${key}.${option}`)}</option>)}</select> : <input type="number" value={form[key]} onChange={(event) => set(key, event.target.value)} />}</label>)}</div><div className="admin-form-actions"><button type="button" onClick={cancel}>{t('admin.cancel')}</button><button className="admin-primary" disabled={saving || !dirty}>{t('admin.save')}</button></div></form><ImagePanel images={images} busy={imageBusy} error={imageError} progress={progress} onFiles={uploadFiles} onMove={(image, direction) => void move(image, direction)} onPrimary={(image) => void primary(image)} onRemove={(image) => void remove(image)} /><ProductActions id={id} product={product} hasImages={images.length > 0} onChanged={() => void load()} /></section>
}

function ImagePanel({ images, busy, error, progress, onFiles, onMove, onPrimary, onRemove }: { images: EditableProductImage[]; busy: boolean; error: string | null; progress: Record<string, number>; onFiles: (event: ChangeEvent<HTMLInputElement>) => void; onMove: (image: EditableProductImage, direction: 'earlier' | 'later') => void; onPrimary: (image: EditableProductImage) => void; onRemove: (image: EditableProductImage) => void }) {
  const { t } = useTranslation()
  return <div className="admin-card admin-images-panel"><div className="admin-panel-heading"><h2>{t('admin.images')}</h2><span>{images.length} {t('admin.ofEight')}</span></div>{error && <div className="admin-error" role="alert">{t(`messages.${error}`, { defaultValue: t('messages.PAGE_500') })}</div>}<label className="admin-file-picker">{t('admin.chooseImages')}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy || images.length >= MAX_IMAGES_PER_PRODUCT} onChange={onFiles} /></label>{Object.entries(progress).map(([name, value]) => <progress key={name} value={value} max="100" aria-label={name} />)}<div className="admin-image-grid">{images.map((image, index) => <div className="admin-image-card" key={image.id}><img src={image.path.startsWith('/') ? image.path : supabase.storage.from('product-images').getPublicUrl(image.path).data.publicUrl} alt="" />{image.is_primary && <Badge>{t('admin.primary')}</Badge>}<span>{index + 1} / {images.length}</span><div className="admin-image-actions"><button disabled={busy || index === 0} aria-label={t('admin.moveEarlier')} onClick={() => onMove(image, 'earlier')}>↑</button><button disabled={busy || index === images.length - 1} aria-label={t('admin.moveLater')} onClick={() => onMove(image, 'later')}>↓</button>{!image.is_primary && <button disabled={busy} onClick={() => onPrimary(image)}>{t('admin.setPrimary')}</button>}<button disabled={busy} className="admin-danger" onClick={() => onRemove(image)}>{t('admin.remove')}</button></div></div>)}</div></div>
}

function ProductActions({ id, product, hasImages, onChanged }: { id: string; product: ProductRow; hasImages: boolean; onChanged: () => void }) {
  const { t } = useTranslation(); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  const run = async (action: ProductAction) => { if (action === 'DELETE' && !window.confirm(t('admin.deleteConfirm'))) return; if (action === 'ARCHIVE' || action === 'UNPUBLISH') if (!window.confirm(t('admin.removeFromCarts'))) return; setBusy(true); setError(null); const result = action === 'DELETE' ? await supabase.from('products').delete().eq('id', id) : await supabase.rpc('admin_set_product_status', { p_product_id: id, p_to: action === 'PUBLISH' || action === 'RESTORE' ? 'ACTIVE' : action === 'UNPUBLISH' ? 'DRAFT' : 'ARCHIVED' }); if (result.error) setError(result.error.message === '23503' ? 'ILLEGAL_PRODUCT_TRANSITION' : errorCode(result.error)); else onChanged(); setBusy(false) }
  const feature = async () => { setBusy(true); const result = await supabase.rpc('admin_set_featured', { p_product_id: id, p_featured: !product.featured }); if (result.error) setError(errorCode(result.error)); else onChanged(); setBusy(false) }
  return <div className="admin-card admin-action-bar">{error && <div className="admin-error" role="alert">{t(`messages.${error}`, { defaultValue: t('messages.PAGE_500') })}</div>}{allowedProductActions(product.status, hasImages).map((action) => <button className={action === 'PUBLISH' ? 'admin-primary' : action === 'DELETE' ? 'admin-danger' : ''} disabled={busy} key={action} onClick={() => void run(action)}>{t(`admin.actionsMap.${action}`)}</button>)}{product.status === 'ACTIVE' && <button disabled={busy} onClick={() => void feature()}>{product.featured ? t('admin.unfeature') : t('admin.feature')}</button>}</div>
}
